name: example
description: Example project for the flutter_translate library
publish_to: none
version: 5.0.0-dev.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate:
    path: ../
  cruiser: ^2.2.1
  
dev_dependencies: 
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/