name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 2.0.1
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_device_locale:
    git: https://github.com/educup/flutter_device_locale.git
  collection: ^1.15.0-nullsafety.4

flutter:
