name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 1.6.0
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_locale: ^0.4.0

flutter:
