name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 4.0.3
homepage: https://jesway.com
repository: https://github.com/Jesway/Flutter-Translate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
