name: example_static_keys
description: Flutter translate example with static localization keys.
publish_to: none
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate:
    path: ../
  flutter_translate_annotations: ^2.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/i18n/

dev_dependencies:
  flutter_translate_gen: ^2.2.0
  build_runner: ^2.1.0
