name: example
description: Example project for the flutter_translate library

version: 1.4.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate:
    path: ../

dev_dependencies:

flutter:

  uses-material-design: true
  assets:
    - assets/i18n/
