name: flutter_translate
description: The internationalization (i18n) library for Flutter. It lets you define translations for your content in different languages and switch between them easily.
version: 1.4.0
author: Florin Bratan <florin@leadcode.io>
homepage: https://github.com/bratan/flutter_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
